### ISSUE TITLE
reduce/scan not support seed in pipe

### ISSUE THREAD

**Issue by darky** [marpple/FxTS#130]
# Bug Report

`reduce` or `scan` functions should support optional `seed` parameter, when used in `pipe`

### 💻 Code

```ts
pipe(
  [1, 2, 3],
  map(n => n * 2),
  reduce((set, n) => set.add(n), new Set<number>()),
)
```

### 🙁 Actual behavior

In runtime: `TypeError: f is not a function`
In compile time: `Argument of type 'unknown' is not assignable to parameter of type '(a: IterableIterator<number>) => unknown'.`

### 🙂 Expected behavior

In runtime: Set(3) { 2, 4, 6 }
In compile time: `set` type properly inferred

**Comment by ppeeou** [comment]
@darky 
Thanks for your interest in FxTS.

We're thinking about the situation you're talking about.
Currently, when reduce and scan support curry, only when the seed is included in the delivered iterable. Curry cannot be used if the seed is different.

The reason is that FxTS views all data as an iterable argument, and when the second argument is viewed as an iterable in the example shown, it is difficult to determine whether the user is trying to evaluate a function or curry.
`reduce((set, n) => set.add(n), new Set<number>());` // want to be curried
`reduce((num, n) => num + n, [1,2,3,4]);` // want to be executed

both `[1,2,3,4]` and `Set<number>` are Iterable
FxTS view
`reduce(fn, Iterable)`

but we feel the need to support.

If you want to use the above logic, you can use it as follows.
```
pipe(
  [1, 2, 3],
  map(n => n * 2),
  res => reduce(
    (set, n) => set.add(n),
    new Set<number>(),
    res
  ),
); // Set(3) { 2, 4, 6 }
```

**Comment by darky** [comment]
```typescript
pipe(
  [1, 2, 3],
  map(n => n * 2),
  res => reduce(
    (set, n) => set.add(n),
    new Set<number>(),
    res
  ),
); // Set(3) { 2, 4, 6 }
```

:arrow_up: LGTM! Thanks!
