### ISSUE TITLE
Better type declaration for `prop` function

### ISSUE THREAD

**Issue by mass2527** [marpple/FxTS#241]
# Suggestion

### Better type for `key` parameter

Currently, invalid keys can be passed without any error.

```ts
const person = {
    name: "jane",
    age: 20,
  };
  
prop("invalid-key", person)
```

To enhance this, I aim to allow only valid keys, such as "name" or "age" in this context.

### Better type for `obj` parameter

Additionally, any value can currently be passed to `obj` as an argument.

```ts
prop("key", () => {})
prop("key", 123)
```

My goal is to improve this by enforcing that only valid objects can be passed.

**Comment by Phryxia** [comment]
@mass2527  cc @ppeeou 

> Currently, invalid keys can be passed without any error.

I think first case is intended behavior. As [#doc](https://fxts.dev/docs/prop) says, it can receive non-key property of given `obj`. Maybe this is becasue `prop` can be used in `pipe` to replace verbose `map` like following

```ts
pipe([
    { x: 0 },
    { x: 1 },
    { y: 2 },
  ],
  map(
    obj => obj.x
  )
)
```

And it has fairly nice return type also! [#source](https://github.com/marpple/FxTS/blob/main/src/prop.ts)

> Additionally, any value can currently be passed to obj as an argument.

Since `function` is also just an object, therefore there is no reason to prohibit it. Even they have some properties.
After value being initiated from `number` or `boolean` literal, they're also being object. they can also have properties. 

For example:

```
const x = 1 // definetly number
x.toPrecision(2)
```

Maybe [#this](https://stackoverflow.com/questions/34067261/is-boxing-coercion-in-javascript) might helps your understanding.

**Comment by ppeeou** [comment]
@mass2527 @Phryxia 
That's right, this is the intended behavior. 

 Since ramdajs also returns the same type, we judged it to be more familiar to users.
https://ramdajs.com/docs/#prop

**Comment by mass2527** [comment]
@Phryxia @ppeeou 
I really appreciate the great explanation!

I initially believed that the `prop` function was only used with pure JavaScript objects, not object values. Now I understand the reason why type definitions were written the way they are currently.
